import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f6f6f9',
        'surface-muted': '#eef1f4',
        'surface-soft': '#f0f3f5',
        'surface-card': '#ffffff',
        'surface-strong': '#dde2e7',
        background: '#f6f6f9',
        'on-background': '#2d2f31',
        'surface-bright': '#f6f6f9',
        'surface-dim': '#d2d4d8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f0f3',
        'surface-container': '#e7e8eb',
        'surface-container-high': '#e1e2e6',
        'surface-container-highest': '#dbdde0',
        'surface-variant': '#dbdde0',
        'surface-tint': '#006668',
        'inverse-surface': '#0c0e10',
        'inverse-on-surface': '#9c9d9f',
        outline: '#757779',
        'outline-variant': '#acadaf',
        ink: '#20262d',
        'ink-muted': '#5b6570',
        primary: '#006668',
        'primary-dark': '#005154',
        'primary-soft': '#d8f8f8',
        'primary-dim': '#00595b',
        'primary-container': '#52f2f5',
        'primary-fixed': '#52f2f5',
        'primary-fixed-dim': '#3de4e7',
        'on-primary': '#befeff',
        'on-primary-container': '#005859',
        'on-primary-fixed': '#004344',
        'on-primary-fixed-variant': '#006264',
        'inverse-primary': '#5dfbfe',
        secondary: '#ab2d00',
        'secondary-soft': '#ffc4b4',
        'secondary-dim': '#962700',
        'secondary-container': '#ffc4b4',
        'secondary-fixed': '#ffc4b4',
        'secondary-fixed-dim': '#ffb19b',
        'on-secondary': '#ffefeb',
        'on-secondary-container': '#882200',
        'on-secondary-fixed': '#661700',
        'on-secondary-fixed-variant': '#982700',
        tertiary: '#005bae',
        'tertiary-dim': '#004f98',
        'tertiary-container': '#80b2ff',
        'tertiary-fixed': '#80b2ff',
        'tertiary-fixed-dim': '#65a4ff',
        'on-tertiary': '#eff2ff',
        'on-tertiary-container': '#003061',
        'on-tertiary-fixed': '#001835',
        'on-tertiary-fixed-variant': '#003971',
        error: '#b31b25',
        'error-dim': '#9f0519',
        'error-container': '#fb5151',
        'on-error': '#ffefee',
        'on-error-container': '#570008',
        'on-surface': '#2d2f31',
        'on-surface-variant': '#5a5c5e',
      },
      fontFamily: {
        heading: ['Manrope', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '1rem',
        xl: '1.5rem',
        '4xl': '2rem',
        '5xl': '2.5rem',
      },
      boxShadow: {
        card: '0 24px 60px -32px rgba(15, 23, 42, 0.24)',
        soft: '0 24px 80px -28px rgba(0, 102, 104, 0.35)',
        panel: '0 18px 40px -28px rgba(15, 23, 42, 0.18)',
        shell: '0 16px 36px -28px rgba(0, 102, 104, 0.18)',
      },
      backgroundImage: {
        'primary-radial':
          'radial-gradient(circle at top, rgba(82, 242, 245, 0.35), rgba(0, 102, 104, 0) 55%)',
        'shell-glow':
          'radial-gradient(circle at top right, rgba(82, 242, 245, 0.18), transparent 24%)',
      },
    },
  },
  plugins: [],
} satisfies Config
